<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-16T12:44:54 IST" name="Suite" finished-at="2024-04-16T12:45:24 IST" duration-ms="29783">
    <groups>
    </groups>
    <test started-at="2024-04-16T12:44:54 IST" name="Test" finished-at="2024-04-16T12:45:24 IST" duration-ms="29783">
      <class name="com.zoho.testcases.TC_LoginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.zoho.testcases.TC_LoginPageTest@2b40ff9c]" started-at="2024-04-16T12:44:55 IST" name="setUp" finished-at="2024-04-16T12:45:07 IST" duration-ms="12646" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLogin()[pri:0, instance:com.zoho.testcases.TC_LoginPageTest@2b40ff9c]" started-at="2024-04-16T12:45:07 IST" name="verifyLogin" finished-at="2024-04-16T12:45:15 IST" duration-ms="7419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method signature="verifyProdPage()[pri:0, instance:com.zoho.testcases.TC_LoginPageTest@2b40ff9c]" started-at="2024-04-16T12:45:15 IST" name="verifyProdPage" finished-at="2024-04-16T12:45:23 IST" duration-ms="8738" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProdPage -->
        <test-method signature="verifyUser()[pri:0, instance:com.zoho.testcases.TC_LoginPageTest@2b40ff9c]" started-at="2024-04-16T12:45:23 IST" name="verifyUser" finished-at="2024-04-16T12:45:24 IST" duration-ms="345" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.zoho.testcases.TC_LoginPageTest.verifyUser(TC_LoginPageTest.java:101)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.zoho.testcases.TC_LoginPageTest@2b40ff9c]" started-at="2024-04-16T12:45:24 IST" name="tearDown" finished-at="2024-04-16T12:45:24 IST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.zoho.testcases.TC_LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
